#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o noclobber

declare TAG_FORMAT='v[0-9]+.[0-9]+.[0-9]+'

echo "[CAUTION] The tag format is '${TAG_FORMAT}'." >&2

IFS=. read -r MAJOR MINOR PATCH < <(
  git tag \
    | grep -E "${TAG_FORMAT}" \
    | sort -t "." -k1,1n -k2,2n -k3,3n \
    | sed -n '$s/^v//p'
) || true

TAG="v${MAJOR:-1}.${MINOR:-0}.$((${PATCH:- -1} + 1))"

git tag "${TAG}" \
  && echo "${TAG}" >&2

git push --tags